[project]
name = "taxi-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-connect>=0.8.18",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "ruff>=0.12.9",
    "tqdm>=4.67.1",
]
